name: Build Custom Keyboard

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: List Available Xcode Versions
        run: ls /Applications | grep Xcode

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build the App (Unsigned)
        run: |
          cd Demo
          xcodebuild build \
            -project Demo.xcodeproj \
            -scheme Demo \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build
          
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r CustomKeyboard.ipa Payload

      - name: Upload IPA for Download
        uses: actions/upload-artifact@v4
        with:
          name: CustomKeyboardApp
          path: Demo/CustomKeyboard.ipa